Projeto_IFisica/Projeto_Erik_Abdala/config/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from app.views import *

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'index'),
    path('area/', area, name = 'areas'),
    path('fisico/', fisico, name = 'fisicos'),
    path('invencao/', invencao, name = 'invencoes'),
    path('questionario/', questionario, name = 'questionarios'),
    path('subarea/', subarea, name = 'subareas'),
    path('topico/', topico, name = 'topicos'),
    path('pessoa/', pessoa, name = 'pessoa'),

]

Projeto_IFisica/Projeto_Erik_Abdala/app/models.py
from django.db import models

# Create your models here.

class Area(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)

    def __str__(self):

        return f'{self.nome}'
    
class Subarea(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)
    area = models.ForeignKey(Area, on_delete = models.CASCADE)

    def __str__(self):

        return f'Subárea: {self.nome} Área: {self.area}'
    
class Topico(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 500)
    subarea = models.ForeignKey(Subarea, on_delete = models.CASCADE)

    def __str__(self):

        return f'{self.nome} {self.descricao} {self.subarea}'
    
class Fisico(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)
    data_nascimento = models.DateField()

    def __str__(self):

        return f'{self.nome} {self.descricao} {self.data_nascimento}'
    
class Invencao(models.Model):

    nome = models.CharField(max_length = 80)
    ano = models.DateField()
    fisico = models.ManyToManyField(Fisico)
    area = models.ManyToManyField(Area)

    def __str__(self):

        return f'{self.nome} {self.ano} {self.fisico} {self.area}'
    
class Questionario(models.Model):

    titulo = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)
    area = models.ForeignKey(Area, on_delete = models.CASCADE)

    def __str__(self):

        return f'{self.titulo} {self.descricao} {self.area}'
    
class Questao(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE)
    titulo = models.CharField(max_length = 80)
    enunciado = models.CharField(max_length = 500)
    alternativa_a = models.CharField(max_length = 300)
    alternativa_b = models.CharField(max_length = 300)
    alternativa_c = models.CharField(max_length = 300)
    alternativa_d = models.CharField(max_length = 300)
    alternativa_e = models.CharField(max_length = 300)
    alternativa_correta = models.CharField(max_length = 1)
    alternativa_submetida = models.CharField(max_length = 1, blank = True, null = True)

    def __str__(self):

        return f'{self.titulo} {self.enunciado} {self.alternativa_a}' \
        f'{self.alternativa_b} {self.alternativa_c} {self.alternativa_d}' \
        f'{self.alternativa_e} {self.alternativa_correta}' \
        f'{self.alternativa_submetida}'
    
class Ocupacao(models.Model):

    nome = models.CharField(max_length = 30)

    def __str__(self):

        return self.nome
    
class Pessoa(models.Model):

    nome = models.CharField(max_length = 80)
    email = models.CharField(max_length = 50)
    ocupacao = models.ForeignKey(Ocupacao, on_delete = models.CASCADE)

    def __str__(self):

        return f'{self.nome} {self.email} {self.ocupacao}'
    
class QuestionarioRespondido(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE)
    pessoa = models.ForeignKey(Pessoa, on_delete = models.CASCADE)
    data_realizacao = models.DateField()
    numero_acertos = models.PositiveIntegerField()

    def __str__(self):

        return f'{self.questionario} {self.pessoa} {self.data_realizacao} {self.numero_acertos}'

Projeto_IFisica/Projeto_Erik_Abdala/app/views.py
from django.shortcuts import render
from . models import *

# Create your views here.

def area(request):

    areas = {
        'areas':Area.objects.all()
    }

    return render(request, 'exibicao/area.html', areas)

def subarea(request):

    subareas = {
        'subareas':Subarea.objects.all()
    }

    return render(request, 'exibicao/subarea.html', subareas)

def topico(request):

    topicos = {
        'topicos':Topico.objects.all()
    }

    return render(request, 'exibicao/topico.html', topicos)

def fisico(request):

    fisicos = {
        'fisicos':Fisico.objects.all()
    }

    return render(request, 'exibicao/fisico.html', fisicos)

def invencao(request):

    invencoes = {
        'invencoes':Invencao.objects.all()
    }

    return render(request, 'exibicao/invencao.html', invencoes)

def questionario(request):

    questionarios = {
        'questionarios':Questionario.objects.all(),
        'questoes':Questao.objects.all()
    }

    return render(request, 'exibicao/questionario.html', questionarios)

def ocupacao(request):

    ocupacoes = {
        'ocupacoes':Ocupacao.objects.all()
    }

    return render(request, 'exibicao/ocupacao.html', ocupacoes)

def pessoa(request):

    pessoas = {
        'pessoas':Pessoa.objects.all()
    }

    return render(request, 'exibicao/pessoa.html', pessoas)

def questionario(request):

    questionarios = {
        'questionarios':Questionario.objects.all()
    }

    return render(request, 'exibicao/questionario.html', questionarios)

Projeto_IFisica/Projeto_Erik_Abdala/app/templates/exibicao/area.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/area">Áreas</a>
          <a href = "/subarea">Subáreas</a>
          <a href = "/topico">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencao">Invenções</a>
          <a href = "/fisico">Físicos</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoa">Integrantes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="/temporario">Tempo</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4">Áreas</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Nome</th>
              <th scope="col">Descrição</th>
            </tr>
            {% for Area in areas %}
          </thead>
          <tbody>
           <td>{{Area.nome}}</td>
           <td>{{Area.descricao}}</td>
          </tbody>
           {% endfor %} 
        </table>
      </div>
    </div>
  </div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Projeto_IFisica/Projeto_Erik_Abdala/app/templates/exibicao/questionario.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/area">Áreas</a>
          <a href = "/subarea">Subáreas</a>
          <a href = "/topico">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencao">Invenções</a>
          <a href = "/fisico">Físicos</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoa">Integrantes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="/temporario">Tempo</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
        <li id = "adm" class="nav-item">
            <a class="nav-link text-dark" href="/questionario">Questionário</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container mt-5">
    <h2 style="text-align: center;" class="mb-4">Tópicos</h2>
    <table>
        {% for Questionario in questionarios %}
        <tbody>
            <tr>
                <td><h1>{{ Questionario.id }}</h1></td>
                <td><h1>{{ Questionario.nome }}</h1></td>
            </tr>
            <tr>
                <td><p>{{ Questionario.descricao }}</p></td>
                <td><p>{{ Questionario.area }}</p></td>
            </tr>
            {% for Questao in Questionario.questao_set.all %}
            <tr>
                <td><p>{{ Questao.enunciado }}</p></td>
            </tr>
            <tr>
                <td><p>{{ Questao.alternativa_a }}</p></td>
            </tr>
            <tr>
                <td><p>{{ Questao.alternativa_b }}</p></td>
            </tr>
            <tr>
                <td><p>{{ Questao.alternativa_c }}</p></td>
            </tr>
            <tr>
                <td><p>{{ Questao.alternativa_d }}</p></td>
            </tr>
            <tr>
                <td><p>{{ Questao.alternativa_e }}</p></td>
            </tr>
            {% endfor %}
        </tbody>
        {% endfor %}
    </table>
</div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Projeto_IFisica/Projeto_Erik_Abdala/app/templates/exibicao/subarea.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/area">Áreas</a>
          <a href = "/subarea">Subáreas</a>
          <a href = "/topico">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencao">Invenções</a>
          <a href = "/fisico">Físicos</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoa">Integrantes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="/temporario">Tempo</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4">Subareas</h2>
        <div class = "table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
                <th scope="col">Área</th>
              </tr>
              {% for Subarea in subareas %}
            </thead>
            <tbody>
              <td style="word-wrap: break-word;min-width: 180px;max-width: 180px;">{{Subarea.nome}}</td>
              <td style="word-wrap: break-word;min-width: 420px;max-width: 420px;">{{Subarea.descricao}}</td>
              <td>{{Subarea.area}}</td>
            </tbody>
            {% endfor %} 
          </table>
        </div>
      </div>
    </div>
  </div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Projeto_IFisica/Projeto_Erik_Abdala/app/templates/exibicao/topico.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/area">Áreas</a>
          <a href = "/subarea">Subáreas</a>
          <a href = "/topico">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencao">Invenções</a>
          <a href = "/fisico">Físicos</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoa">Integrantes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="/temporario">Tempo</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>

<div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4">Tópicos</h2>
    {% for Topico in topicos %}
    <tbody>
        <h1>{{Topico.nome}}</h1>
        <p>{{Topico.descricao}}</p>
        <p>{{Topico.subarea}}</p>
    </tbody>
    {% endfor %}
</div>


  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Projeto_IFisica/Projeto_Erik_Abdala/app/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "area/">Áreas</a>
          <a href = "subarea/">Subáreas</a>
          <a href = "topico/">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "invencao/">Invenções</a>
          <a href = "fisico/">Físicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Questionários<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href="questionario/">Questionário</a>
          <a href="questionario/">Respostas</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="pessoa/">Integrantes</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class = "container" style="margin-top:60px">
    <div class="row">
      <div class="col teste" style = 'margin-right: 20px'>
        <img src = "{% static 'img/banner01.jpg' %}" width = "100%"> 
      </div>
      <div class="col">
        <div class="jumbotron text-center">
          <h1 class="display-4"><b>Olá!</b></h1>
          <h2 class="teste2">Seja bem-vindo(a) ao <b>IFisica!</b></h2>
          <p class="lead">Esta é a página inicial do BalasFlix.</p>
          <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>